# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/onur/devroot/dungeon_game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/onur/devroot/dungeon_game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/onur/devroot/dungeon_game/CMakeFiles /home/onur/devroot/dungeon_game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/onur/devroot/dungeon_game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dungeon_game

# Build rule for target.
dungeon_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dungeon_game
.PHONY : dungeon_game

# fast build rule for target.
dungeon_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/build
.PHONY : dungeon_game/fast

commands.o: commands.c.o
.PHONY : commands.o

# target to build an object file
commands.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/commands.c.o
.PHONY : commands.c.o

commands.i: commands.c.i
.PHONY : commands.i

# target to preprocess a source file
commands.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/commands.c.i
.PHONY : commands.c.i

commands.s: commands.c.s
.PHONY : commands.s

# target to generate assembly for a file
commands.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/commands.c.s
.PHONY : commands.c.s

creature.o: creature.c.o
.PHONY : creature.o

# target to build an object file
creature.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/creature.c.o
.PHONY : creature.c.o

creature.i: creature.c.i
.PHONY : creature.i

# target to preprocess a source file
creature.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/creature.c.i
.PHONY : creature.c.i

creature.s: creature.c.s
.PHONY : creature.s

# target to generate assembly for a file
creature.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/creature.c.s
.PHONY : creature.c.s

game.o: game.c.o
.PHONY : game.o

# target to build an object file
game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/game.c.o
.PHONY : game.c.o

game.i: game.c.i
.PHONY : game.i

# target to preprocess a source file
game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/game.c.i
.PHONY : game.c.i

game.s: game.c.s
.PHONY : game.s

# target to generate assembly for a file
game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/game.c.s
.PHONY : game.c.s

item.o: item.c.o
.PHONY : item.o

# target to build an object file
item.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/item.c.o
.PHONY : item.c.o

item.i: item.c.i
.PHONY : item.i

# target to preprocess a source file
item.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/item.c.i
.PHONY : item.c.i

item.s: item.c.s
.PHONY : item.s

# target to generate assembly for a file
item.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/item.c.s
.PHONY : item.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/main.c.s
.PHONY : main.c.s

player.o: player.c.o
.PHONY : player.o

# target to build an object file
player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/player.c.o
.PHONY : player.c.o

player.i: player.c.i
.PHONY : player.i

# target to preprocess a source file
player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/player.c.i
.PHONY : player.c.i

player.s: player.c.s
.PHONY : player.s

# target to generate assembly for a file
player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/player.c.s
.PHONY : player.c.s

room.o: room.c.o
.PHONY : room.o

# target to build an object file
room.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/room.c.o
.PHONY : room.c.o

room.i: room.c.i
.PHONY : room.i

# target to preprocess a source file
room.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/room.c.i
.PHONY : room.c.i

room.s: room.c.s
.PHONY : room.s

# target to generate assembly for a file
room.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/room.c.s
.PHONY : room.c.s

save.o: save.c.o
.PHONY : save.o

# target to build an object file
save.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/save.c.o
.PHONY : save.c.o

save.i: save.c.i
.PHONY : save.i

# target to preprocess a source file
save.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/save.c.i
.PHONY : save.c.i

save.s: save.c.s
.PHONY : save.s

# target to generate assembly for a file
save.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dungeon_game.dir/build.make CMakeFiles/dungeon_game.dir/save.c.s
.PHONY : save.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dungeon_game"
	@echo "... commands.o"
	@echo "... commands.i"
	@echo "... commands.s"
	@echo "... creature.o"
	@echo "... creature.i"
	@echo "... creature.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... item.o"
	@echo "... item.i"
	@echo "... item.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... room.o"
	@echo "... room.i"
	@echo "... room.s"
	@echo "... save.o"
	@echo "... save.i"
	@echo "... save.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

